frontend:
  name: vdt-frontend
  monitor:
    name: vdt-frontend-monitor
  image:
    repository: nguyenduyanh221204/vdt-frontend
    tag: v1.0.1
  replicas: 1
  containerPort: 80
  metricsPort: 9113
  service:
    name: vdt-frontend-svc
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30001
  resources:
    limits:
      memory: 64Mi
      cpu: 100m

release:
  name: prometheus-stack
