apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.frontend.monitor.name }}
  # namespace: monitoring
  labels:
    app: {{ .Values.frontend.name }}
    release: {{ .Values.release.name }}
spec:
  # Cho phép quét Service ở mọi Namespace
  # namespaceSelector:
  #   any: true
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
