apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.frontend.monitor.name }}
  labels:
    app: {{ .Values.frontend.name }}
    release: {{ .Values.release.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
